sudo: false
language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - python setup.py bdist_egg

# command to run tests
script: nosetests -v

after_success:
    - coveralls
